<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-13T23:36:57 IST" name="Default suite" finished-at="2023-02-13T23:37:54 IST" duration-ms="57581">
    <groups>
    </groups>
    <test started-at="2023-02-13T23:36:57 IST" name="Default test" finished-at="2023-02-13T23:37:54 IST" duration-ms="57581">
      <class name="test.Login">
        <test-method is-config="true" signature="launch()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:36:58 IST" name="launch" finished-at="2023-02-13T23:37:03 IST" duration-ms="4636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:03 IST" name="login" data-provider="provide" finished-at="2023-02-13T23:37:13 IST" duration-ms="10436" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mymaxp290@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abcd@1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:13 IST" name="quit" finished-at="2023-02-13T23:37:14 IST" duration-ms="312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launch()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:14 IST" name="launch" finished-at="2023-02-13T23:37:17 IST" duration-ms="3230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:17 IST" name="login" data-provider="provide" finished-at="2023-02-13T23:37:25 IST" duration-ms="8600" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[alok0218@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345678]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.Login.login(Login.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:26 IST" name="quit" finished-at="2023-02-13T23:37:27 IST" duration-ms="1150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launch()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:27 IST" name="launch" finished-at="2023-02-13T23:37:30 IST" duration-ms="2796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:30 IST" name="login" data-provider="provide" finished-at="2023-02-13T23:37:40 IST" duration-ms="10337" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[targetjee19@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Abcd@1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:40 IST" name="quit" finished-at="2023-02-13T23:37:40 IST" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launch()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:40 IST" name="launch" finished-at="2023-02-13T23:37:44 IST" duration-ms="4202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:44 IST" name="login" data-provider="provide" finished-at="2023-02-13T23:37:54 IST" duration-ms="9590" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hdhdhdhjgu]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.Login.login(Login.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:test.Login@6e20b53a]" started-at="2023-02-13T23:37:54 IST" name="quit" finished-at="2023-02-13T23:37:54 IST" duration-ms="246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- test.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
